#!/bin/sh
# deploy-forced.sh — the forced command of the dg2-deploy key.
#
# THE THREAT (T-2-KEY): a private SSH key sitting in a third-party CI has write
# access to this box. Without a forced command that key IS a shell — whoever
# holds it can read /etc/dg2/env and, from there, the object-storage
# credentials. With this wrapper the key knows how to do exactly two things,
# drop bytes under the release tree and swap a symlink, and nothing else.
#
# It is a wrapper instead of a plain `command="/srv/dg2/bin/deploy.sh"` because
# the SAME key carries the transfer: a naive forced command would run deploy.sh
# in place of `rsync --server`, the transfer would hang, and the operator would
# spend the afternoon blaming the network. So the wrapper accepts exactly two
# shapes and refuses everything else, loudly.
#
# WHY THE RSYNC BRANCH IS A PARSER AND NOT A PREFIX MATCH. It used to be
# `case "$CMD" in 'rsync --server '*) exec $CMD`, which matched the first two
# words and handed the rest over unexamined. The client generates the whole
# argv, and `rsync --server` takes its DESTINATION as the last argument, so
# that sentence at the top of this file was false in four measured ways:
#
#   1. `rsync --server ... . /home/dg2-deploy/.ssh/` was accepted. Overwriting
#      authorized_keys removes this very `command=` and turns the restricted
#      key into a full shell on the next connection. It was the shortest path
#      from "CI compromised" to "root-adjacent shell on the box".
#   2. `rsync --server --sender ...` was accepted, and --sender is rsync's READ
#      direction: anything dg2-deploy can read could be pulled out.
#   3. `--partial-dir=/home/dg2-deploy/.ssh` was accepted even alongside a
#      release-looking destination. An aborted transfer of a file named
#      authorized_keys lands it there — the same escape by a longer road, which
#      is why path-carrying options are checked and not only the destination.
#   4. `exec $CMD` was unquoted with NO `set -f`, so pathname expansion applied
#      to the argv too: `. *` expanded against the deploy user's home. The old
#      comment called the word splitting deliberate and never mentioned the
#      globbing.
#
# WHAT THIS IS NOT. rrsync — shipped with rsync itself, usually at
# /usr/share/doc/rsync/scripts/rrsync — is a complete allowlisting argv parser
# maintained by the people who write rsync's argv, and it is the stronger
# answer. It is not used here because its path is distro-dependent and this
# repository cannot check that a file exists on a box that does not exist yet.
# ops/README.md §4 records the swap as the upgrade to make once the box is
# real. Until then this wrapper denies the shapes above and allowlists the
# paths, which is narrower than a prefix match and wider than rrsync.
#
# Installed in the authorized_keys of dg2-deploy as ONE line:
#   command="/srv/dg2/bin/deploy-forced.sh",no-port-forwarding,
#   no-agent-forwarding,no-pty,no-user-rc ssh-ed25519 AAAA... deploy@ci
#
# Failure contract: stderr as `script:pointer: message`, exit 1.
set -eu

SELF=deploy-forced.sh
DEPLOY=/srv/dg2/bin/deploy.sh

fail() {
    echo "$SELF:$1: $2" >&2
    exit 1
}

# An empty SSH_ORIGINAL_COMMAND means somebody asked for an interactive
# session. There is no shape of that which is legitimate here.
[ -n "${SSH_ORIGINAL_COMMAND:-}" ] \
    || fail 'SSH_ORIGINAL_COMMAND' 'sessão interativa recusada — esta chave não abre shell'

CMD=$SSH_ORIGINAL_COMMAND

case "$CMD" in
    'rsync --server '*)
        # PATHNAME EXPANSION OFF, BEFORE ANYTHING IS SPLIT. The line below has
        # to word-split — rsync's server argv is generated by the client and is
        # not ours to rewrite — but splitting and globbing are two different
        # expansions, and only the first one is wanted. Without `set -f` a `*`
        # in the argv expands against the deploy user's home directory.
        set -f
        # shellcheck disable=SC2086
        set -- $CMD

        # The destination is rsync's LAST argument. Everything before it is
        # checked in the same pass; `continue` on the last one keeps "$@"
        # untouched, so the exec at the bottom runs the argv the client sent
        # and not a reconstruction of it.
        LAST=$#
        DEST=''
        I=0
        for arg in "$@"; do
            I=$((I + 1))
            if [ "$I" -eq "$LAST" ]; then
                DEST=$arg
                continue
            fi
            case "$arg" in
                --sender)
                    fail 'rsync/--sender' 'esta chave só escreve, nunca lê — leitura recusada'
                    ;;
                --daemon)
                    fail 'rsync/--daemon' 'modo daemon recusado — esta chave não abre serviço'
                    ;;
                -e|--rsh|--rsh=*)
                    fail "rsync/$arg" 'shell remoto recusado — esta chave não encadeia conexão'
                    ;;
                --link-dest=*|--copy-dest=*|--compare-dest=*)
                    # Legitimate: --link-dest is what makes five releases cost
                    # almost one (P-12). Its value is a path, so it goes
                    # through the same ruler the destination does.
                    printf '%s' "${arg#*=}" \
                        | grep -Eq '^/srv/dg2/(current|current-server|(releases|server-releases)/[0-9a-f]{40})/?$' \
                        || fail "rsync/$arg" 'árvore de referência fora de /srv/dg2 — recusada'
                    ;;
                */*)
                    # Any OTHER argument carrying a path: --partial-dir,
                    # --temp-dir, --files-from, or a second destination. None
                    # of them appears in the deploy this key exists to carry,
                    # and each of them can put bytes outside the release tree.
                    # Cost of this line, written down on purpose: the day the
                    # CI needs an option that names a path, the deploy fails
                    # HERE with the argument in the message, and this case
                    # statement is where the decision to allow it is recorded.
                    fail "rsync/$arg" 'argumento com caminho fora da árvore de releases'
                    ;;
            esac
        done

        # 40 lowercase hex under one of the two release roots, and nothing
        # else — the same rule deploy.sh and rollback.sh already apply to their
        # own argument, for the same reason: the string becomes a path, so
        # anything carrying `..`, a metacharacter or somebody else's directory
        # is refused at the door rather than sanitised. A trailing slash is
        # allowed because that is the form the CI sends.
        printf '%s' "$DEST" \
            | grep -Eq '^/srv/dg2/(releases|server-releases)/[0-9a-f]{40}/?$' \
            || fail "rsync/$DEST" 'destino fora de /srv/dg2/{releases,server-releases}/<sha de 40 hexadecimais>'

        exec "$@"
        ;;
    "$DEPLOY "*)
        SHA=${CMD#"$DEPLOY "}
        # 40 lowercase hex and nothing else. The argument becomes a path, so
        # anything that could carry `..`, a slash or a metacharacter is refused
        # at the door rather than sanitised — sanitising is a guess, refusing
        # is a decision.
        printf '%s' "$SHA" | grep -Eq '^[0-9a-f]{40}$' \
            || fail 'sha' 'esperado um sha de 40 hexadecimais minúsculos'
        exec "$DEPLOY" "$SHA"
        ;;
    *)
        fail 'SSH_ORIGINAL_COMMAND' 'comando recusado — esta chave só faz rsync e deploy.sh <sha>'
        ;;
esac
