#!/bin/sh
# deploy-forced.sh — the forced command of the dg2-deploy key.
#
# THE THREAT (T-2-KEY): a private SSH key sitting in a third-party CI has write
# access to this box. Without a forced command that key IS a shell — whoever
# holds it can read /etc/dg2/env and, from there, the object-storage
# credentials. With this wrapper the key knows how to do exactly two things,
# drop bytes under the release tree and swap a symlink, and nothing else.
#
# It is a wrapper instead of a plain `command="/srv/dg2/bin/deploy.sh"` because
# the SAME key carries the transfer: a naive forced command would run deploy.sh
# in place of `rsync --server`, the transfer would hang, and the operator would
# spend the afternoon blaming the network. So the wrapper accepts exactly two
# shapes and refuses everything else, loudly.
#
# Installed in the authorized_keys of dg2-deploy as ONE line:
#   command="/srv/dg2/bin/deploy-forced.sh",no-port-forwarding,
#   no-agent-forwarding,no-pty,no-user-rc ssh-ed25519 AAAA... deploy@ci
#
# Failure contract: stderr as `script:pointer: message`, exit 1.
set -eu

SELF=deploy-forced.sh
DEPLOY=/srv/dg2/bin/deploy.sh

fail() {
    echo "$SELF:$1: $2" >&2
    exit 1
}

# An empty SSH_ORIGINAL_COMMAND means somebody asked for an interactive
# session. There is no shape of that which is legitimate here.
[ -n "${SSH_ORIGINAL_COMMAND:-}" ] \
    || fail 'SSH_ORIGINAL_COMMAND' 'sessão interativa recusada — esta chave não abre shell'

CMD=$SSH_ORIGINAL_COMMAND

case "$CMD" in
    'rsync --server '*)
        # The transfer half. rsync's server-side argv is generated by the
        # client and is not ours to rewrite, so it is handed over unsplit-
        # quoted on purpose — the word splitting here is deliberate. What
        # bounds it is the unix account: dg2-deploy owns the release tree and
        # can write nowhere else. If this key ever leaves the CI, the upgrade
        # is a real argv parser (rrsync), not a longer case statement.
        # shellcheck disable=SC2086
        exec $CMD
        ;;
    "$DEPLOY "*)
        SHA=${CMD#"$DEPLOY "}
        # 40 lowercase hex and nothing else. The argument becomes a path, so
        # anything that could carry `..`, a slash or a metacharacter is refused
        # at the door rather than sanitised — sanitising is a guess, refusing
        # is a decision.
        printf '%s' "$SHA" | grep -Eq '^[0-9a-f]{40}$' \
            || fail 'sha' 'esperado um sha de 40 hexadecimais minúsculos'
        exec "$DEPLOY" "$SHA"
        ;;
    *)
        fail 'SSH_ORIGINAL_COMMAND' 'comando recusado — esta chave só faz rsync e deploy.sh <sha>'
        ;;
esac
